### ISSUE TITLE
Modifying border creates visual glitch

### ISSUE THREAD

**Issue by benplumley** [atom/bracket-matcher#106]
I have the following in my styles.less

    atom-text-editor::shadow .bracket-matcher {
      background-color: #49483E;
      border: 1px dotted lime;
    }

which creates this effect:

![](http://i.gyazo.com/e7da0e083acd54827bde6a1325ac4dbf.png)

However, as of atom 177, it also creates this glitch along the top of the editor window:

![](http://i.gyazo.com/55c7634731611dde5b335f7eeeec4517.png)

which appears above line 1 of the file (ie does not show unless the file is scrolled to the top).

**Comment by kevinsawicki** [comment]
I think I gave you back CSS on that other issue.

Bracket matchers uses Atom's decorations API now so proper CSS would be:

```css
atom-text-editor::shadow .bracket-matcher .region {
  background-color: #49483E;
  border: 1px dotted lime;
}
```
