### ISSUE TITLE
Change of matched bracket styling

### ISSUE THREAD

**Issue by finanalyst** [atom/bracket-matcher#398]
## Summary
I want to see brackets more clearly.
The a bracket and its matching pair are highlighted by a red underline.
I find this difficult to see.
I would like to have the whole character hightlighted, or to be able to change the highlight effect.

## Describe alternatives you've considered
I have looked for where to find the css for this bracket highlighting effect.
I have used developer tools to find how highlights are implemented.

## Additional context
None

**Comment by pragmaticpragma** [comment]
Hello there,
To change styling open your stylesheet which can be opened from the file tab and insert this code:
```CSS
atom-text-editor .bracket-matcher .region{
  margin-top: 1px !important;
  border-bottom: 2px inset rgba(0, 255, 0, 1);
  border: 2px inset rgba(0, 255, 0, 1);
  border-radius: 10%;
  background-color: rgba(0, 255, 0, .2);
}
```

The important values here are border-bottom, border, and background-color; the others are only slight alterations to location on the page and aren't that important.
The background-color assignment can be an rgba code or an 8 or 4 digit hex code; the last digit in that code must always represent something greater than zero or the highlight won't show up.
