### ISSUE TITLE
Add class to brackets for styling

### ISSUE THREAD

**Issue by danlshields** [atom/bracket-matcher#46]
One of the coolest features of atom is being able to customize things using stylesheets. However, it seems you can't style matching brackets because bracket-matcher only inserts DOM into the under layer. I'd like to be able to style matching brackets, for example:

``` css
.matching-bracket {
  text-shadow: 2px 2px #ff0000;
}
```

**Comment by InSuperposition** [comment]
:+1:

**Comment by lee-dohm** [comment]
I feel like this revising of the Issue makes it a duplicate of atom/atom#2886. Essentially, the current Decorations API (and its precursors) can create layers over or under the text z-order-wise, but do not modify the classes of the text itself. Nor do they offer a means where an over layer can easily duplicate the text which it is obscuring in order to make it look like it is modifying the text.

So really, this is a bigger problem than just the bracket-matcher package.

**Comment by bassu** [comment]
+1

**Comment by lope** [comment]
+1
I would really benefit from this. I would make a yellow block around the matching bracket. The tiny blue underline is very hard to notice in a massive chunk of code.

**Comment by lee-dohm** [comment]
@lope You can make a yellow box around the matching bracket. You just can't change the style of the text itself.

**Comment by lope** [comment]
@lee-dohm great, how can I set a background color on the matching bracket? I've seen a few other people such as @majcherek2048 ask about this as well?

**Comment by lee-dohm** [comment]
```css
atom-text-editor::shadow {
  .bracket-matcher .region {
    background-color: yellow;
    border: 1px solid black;
  }
}
```
